// Mocks generated by Mockito 5.4.6 from annotations
// in gasolina/test/unit/features/fuel_entries/data/repositories/fuel_entry_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:gasolina/features/fuel_entries/data/datasources/fuel_entry_local_datasource.dart'
    as _i4;
import 'package:gasolina/features/fuel_entries/data/models/fuel_entry_model.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuelEntryModel_1 extends _i1.SmartFake
    implements _i3.FuelEntryModel {
  _FakeFuelEntryModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FuelEntryLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFuelEntryLocalDataSource extends _i1.Mock
    implements _i4.FuelEntryLocalDataSource {
  MockFuelEntryLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _FakeDatabase_0(this, Invocation.getter(#database)),
          )
          as _i2.Database);

  @override
  _i5.Future<_i3.FuelEntryModel> addEntry(_i3.FuelEntryModel? entry) =>
      (super.noSuchMethod(
            Invocation.method(#addEntry, [entry]),
            returnValue: _i5.Future<_i3.FuelEntryModel>.value(
              _FakeFuelEntryModel_1(
                this,
                Invocation.method(#addEntry, [entry]),
              ),
            ),
          )
          as _i5.Future<_i3.FuelEntryModel>);

  @override
  _i5.Future<List<_i3.FuelEntryModel>> getAllEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEntries, []),
            returnValue: _i5.Future<List<_i3.FuelEntryModel>>.value(
              <_i3.FuelEntryModel>[],
            ),
          )
          as _i5.Future<List<_i3.FuelEntryModel>>);

  @override
  _i5.Future<_i3.FuelEntryModel> getEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryById, [id]),
            returnValue: _i5.Future<_i3.FuelEntryModel>.value(
              _FakeFuelEntryModel_1(
                this,
                Invocation.method(#getEntryById, [id]),
              ),
            ),
          )
          as _i5.Future<_i3.FuelEntryModel>);

  @override
  _i5.Future<_i3.FuelEntryModel> updateEntry(_i3.FuelEntryModel? entry) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue: _i5.Future<_i3.FuelEntryModel>.value(
              _FakeFuelEntryModel_1(
                this,
                Invocation.method(#updateEntry, [entry]),
              ),
            ),
          )
          as _i5.Future<_i3.FuelEntryModel>);

  @override
  _i5.Future<void> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
