// Mocks generated by Mockito 5.4.6 from annotations
// in gasolina/test/unit/features/fuel_entries/domain/usecases/get_all_fuel_entries_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gasolina/core/errors/failures.dart' as _i5;
import 'package:gasolina/features/fuel_entries/domain/entities/fuel_entry.dart'
    as _i6;
import 'package:gasolina/features/fuel_entries/domain/repositories/fuel_entry_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FuelEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFuelEntryRepository extends _i1.Mock
    implements _i3.FuelEntryRepository {
  MockFuelEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.FuelEntry>>> getAllEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEntries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.FuelEntry>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.FuelEntry>>(
                    this,
                    Invocation.method(#getAllEntries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.FuelEntry>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>> getEntryById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEntryById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.FuelEntry>(
                    this,
                    Invocation.method(#getEntryById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>> addEntry(
    _i6.FuelEntry? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addEntry, [entry]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.FuelEntry>(
                    this,
                    Invocation.method(#addEntry, [entry]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>> updateEntry(
    _i6.FuelEntry? entry,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEntry, [entry]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>.value(
                  _FakeEither_0<_i5.Failure, _i6.FuelEntry>(
                    this,
                    Invocation.method(#updateEntry, [entry]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.FuelEntry>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> deleteEntry(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#deleteEntry, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
